title: Sunday Raceday
description: "We're here to race and have fun."
show_downloads: false
google_analytics:
theme: jekyll-theme-leap-day
# defaults:
#   - scope:
#       path: ""
#     values:
#       layout: "page"
#   - scope:
#       path: "streamers"
#       type: "posts"
#     values:
#       layout: "post"
#       streamer_logo: ../images/logo-default.png
#       banner: ../images/banner-default.png
